services:
  app:
    image: mysociety/wft-question-analysis:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/wft_question_analysis      
    volumes:
      - ./:/workspaces/wft_question_analysis/